import subprocess

seeds = [
    1071,
    6637,
    3918,
    4420,
    5251,
]
l2d_type_lst = ['pop', 'single']
p_out_lst = [0.1, 0.2, 0.4, 0.6, 0.8, 0.95]

for seed in seeds:
    # subprocess.check_output(f"python train_classifier_ham10000.py --epochs 3 --seed {seed}", shell=True, stderr=subprocess.STDOUT, universal_newlines=True)
    print(f"eai job new --data snow.putra_manggala.coco0:/Data:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --cpu 8 --mem 12 -- python train_classifier_ham10000.py --seed {seed}")
    for l2d_type in l2d_type_lst:
        for p_out in p_out_lst:
            print(f"eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --seed {seed} --l2d {l2d_type} --p_out {p_out}")
            #TODO: generate docker calls
            # print(f"Seed: {seed}, Alg: {l2d_type}, p_out: {p_out}")
            # subprocess.check_output(f"python main_ham10000.py --warmstart_epochs 3 --seed {seed} --p_out {p_out} --l2d {l2d_type}", shell=True, stderr=subprocess.STDOUT, universal_newlines=True)


# eai job new --data snow.putra_manggala.coco0:/Data:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --cpu 8 --mem 12 -- python train_classifier_ham10000.py --epochs 3 --seed 1071

# eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --warmstart_epochs 3 --seed 1071

#
# eai job new --data snow.putra_manggala.coco0:/Data:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --cpu 8 --mem 12 -- python train_classifier_ham10000.py --seed 1071
# eai job new --data snow.putra_manggala.coco0:/Data:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --cpu 8 --mem 12 -- python train_classifier_ham10000.py --seed 6637
# eai job new --data snow.putra_manggala.coco0:/Data:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --cpu 8 --mem 12 -- python train_classifier_ham10000.py --seed 3918
# eai job new --data snow.putra_manggala.coco0:/Data:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --cpu 8 --mem 12 -- python train_classifier_ham10000.py --seed 4420
# eai job new --data snow.putra_manggala.coco0:/Data:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --cpu 8 --mem 12 -- python train_classifier_ham10000.py --seed 5251



# eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --seed 1071 --l2d pop --p_out 0.1
# eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --seed 1071 --l2d pop --p_out 0.2
# eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --seed 1071 --l2d pop --p_out 0.4
# eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --seed 1071 --l2d pop --p_out 0.6
# eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --seed 1071 --l2d pop --p_out 0.8
# eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --seed 1071 --l2d pop --p_out 0.95
# eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --seed 1071 --l2d single --p_out 0.1
# eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --seed 1071 --l2d single --p_out 0.2
# eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --seed 1071 --l2d single --p_out 0.4
# eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --seed 1071 --l2d single --p_out 0.6
# eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --seed 1071 --l2d single --p_out 0.8
# eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --seed 1071 --l2d single --p_out 0.95
#
#
# eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --seed 6637 --l2d pop --p_out 0.1
# eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --seed 6637 --l2d pop --p_out 0.2
# eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --seed 6637 --l2d pop --p_out 0.4
# eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --seed 6637 --l2d pop --p_out 0.6
# eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --seed 6637 --l2d pop --p_out 0.8
# eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --seed 6637 --l2d pop --p_out 0.95
# eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --seed 6637 --l2d single --p_out 0.1
# eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --seed 6637 --l2d single --p_out 0.2
# eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --seed 6637 --l2d single --p_out 0.4
# eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --seed 6637 --l2d single --p_out 0.6
# eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --seed 6637 --l2d single --p_out 0.8
# eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --seed 6637 --l2d single --p_out 0.95
# eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --seed 3918 --l2d pop --p_out 0.1
# eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --seed 3918 --l2d pop --p_out 0.2
# eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --seed 3918 --l2d pop --p_out 0.4
# eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --seed 3918 --l2d pop --p_out 0.6
# eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --seed 3918 --l2d pop --p_out 0.8
# eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --seed 3918 --l2d pop --p_out 0.95
# eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --seed 3918 --l2d single --p_out 0.1
# eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --seed 3918 --l2d single --p_out 0.2
# eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --seed 3918 --l2d single --p_out 0.4
# eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --seed 3918 --l2d single --p_out 0.6
# eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --seed 3918 --l2d single --p_out 0.8
# eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --seed 3918 --l2d single --p_out 0.95
# eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --seed 4420 --l2d pop --p_out 0.1
# eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --seed 4420 --l2d pop --p_out 0.2
# eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --seed 4420 --l2d pop --p_out 0.4
# eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --seed 4420 --l2d pop --p_out 0.6
# eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --seed 4420 --l2d pop --p_out 0.8
# eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --seed 4420 --l2d pop --p_out 0.95
# eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --seed 4420 --l2d single --p_out 0.1
# eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --seed 4420 --l2d single --p_out 0.2
# eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --seed 4420 --l2d single --p_out 0.4
# eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --seed 4420 --l2d single --p_out 0.6
# eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --seed 4420 --l2d single --p_out 0.8
# eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --seed 4420 --l2d single --p_out 0.95
# eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --seed 5251 --l2d pop --p_out 0.1
# eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --seed 5251 --l2d pop --p_out 0.2
# eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --seed 5251 --l2d pop --p_out 0.4
# eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --seed 5251 --l2d pop --p_out 0.6
# eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --seed 5251 --l2d pop --p_out 0.8
# eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --seed 5251 --l2d pop --p_out 0.95
# eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --seed 5251 --l2d single --p_out 0.1
# eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --seed 5251 --l2d single --p_out 0.2
# eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --seed 5251 --l2d single --p_out 0.4
# eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --seed 5251 --l2d single --p_out 0.6
# eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --seed 5251 --l2d single --p_out 0.8
# eai job new --data snow.putra_manggala.coco0:/dataset:rw --data snow.putra_manggala.pretrained_model:/pretrained_model:rw --data snow.putra_manggala.results:/results:rw -i registry.console.elementai.com/$ORG_NAME.$ACCOUNT_NAME/perm_transformer0 --gpu 1 --gpu-mem 24 --cpu 8 --mem 12 -- python main_ham10000.py --seed 5251 --l2d single --p_out 0.95